# Generated by Django 5.1.3 on 2024-11-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DecApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_details',
            name='Delivery_Date',
            field=models.DateField(),
        ),
    ]
